name: Publish Package to npmjs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g yarn
      - run: yarn add -D typescript koishi yml-register esbuild tsc yakumo yakumo-esbuild yakumo-tsc
      - run: yarn && yarn build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
